spring:
  docker:
    compose:
      file: compose.yaml
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail_username}
    password: ${mail_password}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${client_id}
            client-secret: ${client_secret}
            scope:
              - read:user
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: off
app:
  jwt:
    key: ${jwt_key}
    algorithm: ${jwt_algorithm}
    issuer: ${jwt_issuer}
    expiresIn: 30m
  mime:
    reset-password:
      resource: /templates/reset-password.html
      url: http://localhost:3000/reset-password?token=


