create table users (
    id           bigint generated by default as identity
        constraint pk_users
            primary key,
    username     varchar(255),
    password     varchar(255),
    phone_number varchar(255),
    email        varchar(255)
        constraint unique_email
            unique,
    created_at   timestamp,
    updated_at   timestamp
);

alter table users
    owner to "user";


create table contact_profile (
    id         bigint generated by default as identity
        constraint pk_contact
            primary key,
    first_name varchar(255),
    last_name  varchar(255),
    title      varchar(255),
    user_id    bigint
        constraint fk_contact_on_user
            references users
);

alter table contact_profile
    owner to "user";


create table email_address (
    id                 bigint generated by default as identity
        constraint pk_email
            primary key,
    email              varchar(255),
    email_label        varchar(255),
    contact_profile_id bigint
        constraint fk_email_on_contact
            references contact_profile
);

alter table email_address
    owner to "user";


create table phone_number (
    id                 bigint generated by default as identity
        constraint pk_phone
            primary key,
    number             varchar,
    phone_label        varchar(255),
    contact_profile_id bigint
        constraint fk_phone_on_contact
            references contact_profile
);

alter table phone_number
    owner to "user";


create table mime (
    uuid       uuid not null
        constraint pk_mime
            primary key,
    user_id    bigint
        constraint fk_mime_on_user
            references users,
    created_at timestamp
);

alter table mime
    owner to "user";

