name: development workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'oracle'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

on:
  pull_request:
    branches:
      - master